version: 2

models:

  - name: dim_clientes
    description: >
      Dimensão de clientes da LH Nautical.
      Contém informações cadastrais e geográficas dos clientes.

    columns:
      - name: client_pk
        description: Identificador único do cliente.
        tests:
          - unique
          - not_null

      - name: client_email
        description: Email do cliente.

      - name: client_estado
        description: Estado de residência do cliente.

      - name: client_cidade
        description: Cidade de residência do cliente.


  - name: dim_produtos
    description: >
      Dimensão de produtos comercializados pela LH Nautical.

    columns:
      - name: product_pk
        description: Identificador único do produto.
        tests:
          - unique
          - not_null
      - name: product_name
        description: Nome do produto.

      - name: product_category
        description: Categoria padronizada do produto.

      - name: product_price
        description: Preço unitário do produto.


  - name: dim_datas
    description: >
      Dimensão de datas utilizada para análises temporais e sazonalidade.

    columns:
    - name: date_day
      description: Data no formato dia/mês/ano.

    - name: day
      description: Dia do mês extraído da data.

    - name: month
      description : Mês extraído da data.
      
    - name: year
      description: Ano extraído da data.

    - name: day_of_week_num
      description: Número do dia da semana (1=Segunda, 7=Domingo).

    - name: day_of_week_name
      description: Nome do dia da semana.

    - name: is_weekend
      description: Indica se a data é final de semana.

  #============================ FATOS==========================================

  - name: fct_vendas
    description: >
      Tabela fato de vendas.
      Representa a venda de um produto para um cliente em uma data específica.

    columns:
      - name: ven_id
        description: Identificador único da venda.
        tests:
          - unique
          - not_null

      - name: data_vend
        description: Data da venda.
        tests:
          - relationships:
              arguments:
                to: ref('dim_datas')
                field: date_day

      - name: client_id
        description: Identificador do cliente.
        tests:
          - relationships:
              arguments:
                to: ref('dim_clientes')
                field: client_pk

      - name: product_id
        description: Identificador do produto vendido.
        tests:
          - relationships:
              arguments:
                to: ref('dim_produtos')
                field: product_pk
      - name: quant_vend
        description: Quantidade do produto vendida.
      - name: total_vend_usd
        description: Valor total da venda.
      - name: product_cost_usd
        description: Custo unitário do produto no momento da venda.
      - name: custo_total_usd
        description: Custo total da venda (quantidade * custo unitário).
      - name: lucro_estimado_usd
        description: Lucro estimado da venda (valor total - custo total).


  - name: fct_vendas_margem
    description:
      Tabela fato de margem por produto.
      Calcula custo, receita e lucro estimado considerando o custo vigente no momento da venda.

    columns:
      - name: venda_id
        description: Identificador único da venda.
        tests:
          - unique
          - not_null

      - name: data_vend
        description: Data da venda.
        tests:
          - relationships:
              arguments:
                to: ref('dim_datas')
                field: date_day

      - name: product_id
        description: Identificador do produto vendido.
        tests:
            - relationships:
                arguments:
                  to: ref('dim_produtos')
                  field: product_pk
      - name: quant_vend
        description: Quantidade do produto vendida.
      - name: total_vend_usd
        description: Valor total da venda.
      - name: avg_product_cost_usd    
        description: Custo unitário médio do produto no momento da venda, considerando a média dos custos dos produtos vendidos naquele dia.
      - name: custo_total_usd
        description: Custo total da venda em USD (quantidade * custo unitário em usd).
      - name: lucro_estimado_usd
        description: Lucro estimado da venda em USD (valor total convertido para USD - custo total em USD).


  - name: fct_vendas_dia
    description: >
      Tabela fato de vendas por dia.
      Representa a venda de um produto para um cliente em uma data específica, com informações adicionais para análises temporais.

    columns:
      - name: day_of_week_name
        description: Nome do dia da semana.
      - name: vendas_medias
        description: Quantidade média de vendas por dia da semana.